[package]
name = "men_in_tights"
description = "Unofficial Robinhood API bindings for Rust. 📈"


edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/ncipollo/men-in-tights"
version = "0.0.1"

[dependencies]
